// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqwWwvZhvxpb6jrk2psbJXDoy6OEZQvSo',
    appId: '1:334860453428:web:776c893b8d9ed6f1ceec61',
    messagingSenderId: '334860453428',
    projectId: 'flutter-chat-app-523a2',
    authDomain: 'flutter-chat-app-523a2.firebaseapp.com',
    storageBucket: 'flutter-chat-app-523a2.firebasestorage.app',
    measurementId: 'G-YH7P23V0VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHs3FF6a8hP2VP7uBp2A9FLSHQL9wM9fA',
    appId: '1:334860453428:android:667bfc90c8e42258ceec61',
    messagingSenderId: '334860453428',
    projectId: 'flutter-chat-app-523a2',
    storageBucket: 'flutter-chat-app-523a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6qlvdVOIfwJYE_PeJIVsk0ikUdd_jBhw',
    appId: '1:334860453428:ios:b17eb2b33fa5aa9bceec61',
    messagingSenderId: '334860453428',
    projectId: 'flutter-chat-app-523a2',
    storageBucket: 'flutter-chat-app-523a2.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6qlvdVOIfwJYE_PeJIVsk0ikUdd_jBhw',
    appId: '1:334860453428:ios:b17eb2b33fa5aa9bceec61',
    messagingSenderId: '334860453428',
    projectId: 'flutter-chat-app-523a2',
    storageBucket: 'flutter-chat-app-523a2.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqwWwvZhvxpb6jrk2psbJXDoy6OEZQvSo',
    appId: '1:334860453428:web:9068a073a3549b51ceec61',
    messagingSenderId: '334860453428',
    projectId: 'flutter-chat-app-523a2',
    authDomain: 'flutter-chat-app-523a2.firebaseapp.com',
    storageBucket: 'flutter-chat-app-523a2.firebasestorage.app',
    measurementId: 'G-9C4QVLB62L',
  );
}
